import { Prisma, PrismaClient } from "./prisma";

const prisma = new PrismaClient();

export const userData: Prisma.UserCreateInput[] = [
  {
    name: "Alice",
    email: "alice@prisma.io",
    role: "MANAGER",
    tasks: {
      create: [
        {
          title: "Task001",
          slug: "task001",
          description: "Write unit tests for billing",
          status: "CANCELED",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-01T08:09:36Z",
          isSeed: true,
        },
        {
          title: "Task005",
          slug: "task005",
          description: "Fix race condition in tasks",
          status: "CANCELED",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-02T16:48:00Z",
          isSeed: true,
        },
        {
          title: "Task009",
          slug: "task009",
          description: "Fix race condition in tasks",
          status: "IN_PROGRESS",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-04T01:26:24Z",
          isSeed: true,
        },
        {
          title: "Task013",
          slug: "task013",
          description: "Optimize image loading",
          status: "TODO",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-05T10:04:48Z",
          isSeed: true,
        },
        {
          title: "Task017",
          slug: "task017",
          description: "Add 2FA support",
          status: "CANCELED",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-06-06T18:43:12Z",
          isSeed: true,
        },
        {
          title: "Task021",
          slug: "task021",
          description: "Optimize lambda cold starts",
          status: "CANCELED",
          priority: "LOW",
          type: "FEATURE",
          createdAt: "2025-06-08T03:21:36Z",
          isSeed: true,
        },
        {
          title: "Task025",
          slug: "task025",
          description: "Implement role-based access control",
          status: "TODO",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-09T12:00:00Z",
          isSeed: true,
        },
        {
          title: "Task029",
          slug: "task029",
          description: "Migrate to new API version",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "FEATURE",
          createdAt: "2025-06-10T20:38:24Z",
          isSeed: true,
        },
        {
          title: "Task033",
          slug: "task033",
          description: "Create admin audit logs",
          status: "DONE",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-12T05:16:48Z",
          isSeed: true,
        },
        {
          title: "Task037",
          slug: "task037",
          description: "Add export to CSV",
          status: "TODO",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-13T13:55:12Z",
          isSeed: true,
        },
        {
          title: "Task041",
          slug: "task041",
          description: "Design new onboarding flow",
          status: "TODO",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-14T22:33:36Z",
          isSeed: true,
        },
        {
          title: "Task045",
          slug: "task045",
          description: "Improve error pages",
          status: "TODO",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-16T07:12:00Z",
          isSeed: true,
        },
        {
          title: "Task049",
          slug: "task049",
          description: "Implement role-based access control",
          status: "TODO",
          priority: "LOW",
          type: "FEATURE",
          createdAt: "2025-06-17T15:50:24Z",
          isSeed: true,
        },
        {
          title: "Task053",
          slug: "task053",
          description: "Improve error pages",
          status: "DONE",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-19T00:28:48Z",
          isSeed: true,
        },
        {
          title: "Task057",
          slug: "task057",
          description: "Improve mobile responsiveness",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-20T09:07:12Z",
          isSeed: true,
        },
        {
          title: "Task061",
          slug: "task061",
          description: "Add export to CSV",
          status: "DONE",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-21T17:45:36Z",
          isSeed: true,
        },
        {
          title: "Task065",
          slug: "task065",
          description: "Optimize query performance",
          status: "DONE",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-23T02:24:00Z",
          isSeed: true,
        },
        {
          title: "Task069",
          slug: "task069",
          description: "Fix logout redirect bug",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-24T11:02:24Z",
          isSeed: true,
        },
        {
          title: "Task073",
          slug: "task073",
          description: "Refactor feature toggles",
          status: "CANCELED",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-25T19:40:48Z",
          isSeed: true,
        },
        {
          title: "Task077",
          slug: "task077",
          description: "Optimize WebSocket connections",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-27T04:19:12Z",
          isSeed: true,
        },
        {
          title: "Task081",
          slug: "task081",
          description: "Design new onboarding flow",
          status: "CANCELED",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-28T12:57:36Z",
          isSeed: true,
        },
        {
          title: "Task085",
          slug: "task085",
          description: "Add skeleton loaders",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-29T21:36:00Z",
          isSeed: true,
        },
        {
          title: "Task089",
          slug: "task089",
          description: "Test backup and restore",
          status: "CANCELED",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-07-01T06:14:24Z",
          isSeed: true,
        },
        {
          title: "Task093",
          slug: "task093",
          description: "Improve mobile responsiveness",
          status: "TODO",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-07-02T14:52:48Z",
          isSeed: true,
        },
        {
          title: "Task097",
          slug: "task097",
          description: "Improve error pages",
          status: "TODO",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-07-03T23:31:12Z",
          isSeed: true,
        },
      ],
    },
  },
  {
    name: "Test",
    email: "test@prisma.io",
    role: "USER",
  },
  {
    name: "Bob",
    email: "bob@prisma.io",
    role: "ADMIN",
    tasks: {
      create: [
        {
          title: "Task002",
          slug: "task002",
          description: "Add dark mode support",
          status: "TODO",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-01T16:19:12Z",
          isSeed: true,
        },
        {
          title: "Task006",
          slug: "task006",
          description: "Improve mobile responsiveness",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "BUG",
          createdAt: "2025-06-03T00:57:36Z",
          isSeed: true,
        },
        {
          title: "Task010",
          slug: "task010",
          description: "Document public API",
          status: "TODO",
          priority: "HIGH",
          type: "ENHANCEMENT",
          createdAt: "2025-06-04T09:36:00Z",
          isSeed: true,
        },
        {
          title: "Task014",
          slug: "task014",
          description: "Implement usage analytics",
          status: "TODO",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-05T18:14:24Z",
          isSeed: true,
        },
        {
          title: "Task018",
          slug: "task018",
          description: "Optimize query performance",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-07T02:52:48Z",
          isSeed: true,
        },
        {
          title: "Task022",
          slug: "task022",
          description: "Support custom domains",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "FEATURE",
          createdAt: "2025-06-08T11:31:12Z",
          isSeed: true,
        },
        {
          title: "Task026",
          slug: "task026",
          description: "Optimize image loading",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-09T20:09:36Z",
          isSeed: true,
        },
        {
          title: "Task030",
          slug: "task030",
          description: "Test rate limiting",
          status: "TODO",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-11T04:48:00Z",
          isSeed: true,
        },
        {
          title: "Task034",
          slug: "task034",
          description: "Support custom domains",
          status: "CANCELED",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-12T13:26:24Z",
          isSeed: true,
        },
        {
          title: "Task038",
          slug: "task038",
          description: "Enhance code review checklist",
          status: "CANCELED",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-06-13T22:04:48Z",
          isSeed: true,
        },
        {
          title: "Task042",
          slug: "task042",
          description: "Implement email templates",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-15T06:43:12Z",
          isSeed: true,
        },
        {
          title: "Task046",
          slug: "task046",
          description: "Support custom domains",
          status: "CANCELED",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-16T15:21:36Z",
          isSeed: true,
        },
        {
          title: "Task050",
          slug: "task050",
          description: "Add 2FA support",
          status: "DONE",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-18T00:00:00Z",
          isSeed: true,
        },
        {
          title: "Task054",
          slug: "task054",
          description: "Add support for multi-language",
          status: "TODO",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-19T08:38:24Z",
          isSeed: true,
        },
        {
          title: "Task058",
          slug: "task058",
          description: "Implement role-based access control",
          status: "TODO",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-20T17:16:48Z",
          isSeed: true,
        },
        {
          title: "Task062",
          slug: "task062",
          description: "Support custom domains",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-22T01:55:12Z",
          isSeed: true,
        },
        {
          title: "Task066",
          slug: "task066",
          description: "Migrate to new API version",
          status: "TODO",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-23T10:33:36Z",
          isSeed: true,
        },
        {
          title: "Task070",
          slug: "task070",
          description: "Optimize lambda cold starts",
          status: "IN_PROGRESS",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-24T19:12:00Z",
          isSeed: true,
        },
        {
          title: "Task074",
          slug: "task074",
          description: "Create admin audit logs",
          status: "DONE",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-26T03:50:24Z",
          isSeed: true,
        },
        {
          title: "Task078",
          slug: "task078",
          description: "Implement role-based access control",
          status: "DONE",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-27T12:28:48Z",
          isSeed: true,
        },
        {
          title: "Task082",
          slug: "task082",
          description: "Fix cache invalidation bug",
          status: "IN_PROGRESS",
          priority: "LOW",
          type: "FEATURE",
          createdAt: "2025-06-28T21:07:12Z",
          isSeed: true,
        },
        {
          title: "Task086",
          slug: "task086",
          description: "Add webhook support",
          status: "DONE",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-30T05:45:36Z",
          isSeed: true,
        },
        {
          title: "Task090",
          slug: "task090",
          description: "Update dependencies",
          status: "DONE",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-07-01T14:24:00Z",
          isSeed: true,
        },
        {
          title: "Task094",
          slug: "task094",
          description: "Optimize WebSocket connections",
          status: "TODO",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-07-02T23:02:24Z",
          isSeed: true,
        },
        {
          title: "Task098",
          slug: "task098",
          description: "Refactor feature toggles",
          status: "DONE",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-07-04T07:40:48Z",
          isSeed: true,
        },
      ],
    },
  },
  {
    name: "Michal",
    email: "michal@prisma.io",
    role: "DEVELOPER",
    tasks: {
      create: [
        {
          title: "Task003",
          slug: "task003",
          description: "Support custom domains",
          status: "CANCELED",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-02T00:28:48Z",
          isSeed: true,
        },
        {
          title: "Task007",
          slug: "task007",
          description: "Set up error tracking",
          status: "TODO",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-03T09:07:12Z",
          isSeed: true,
        },
        {
          title: "Task011",
          slug: "task011",
          description: "Design new user profile page",
          status: "CANCELED",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-04T17:45:36Z",
          isSeed: true,
        },
        {
          title: "Task015",
          slug: "task015",
          description: "Refactor GraphQL schema",
          status: "DONE",
          priority: "LOW",
          type: "FEATURE",
          createdAt: "2025-06-06T02:24:00Z",
          isSeed: true,
        },
        {
          title: "Task019",
          slug: "task019",
          description: "Improve build pipeline",
          status: "DONE",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-07T11:02:24Z",
          isSeed: true,
        },
        {
          title: "Task023",
          slug: "task023",
          description: "Refactor notification service",
          status: "IN_PROGRESS",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-08T19:40:48Z",
          isSeed: true,
        },
        {
          title: "Task027",
          slug: "task027",
          description: "Fix cache invalidation bug",
          status: "TODO",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-06-10T04:19:12Z",
          isSeed: true,
        },
        {
          title: "Task031",
          slug: "task031",
          description: "Add password strength meter",
          status: "TODO",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-11T12:57:36Z",
          isSeed: true,
        },
        {
          title: "Task035",
          slug: "task035",
          description: "Design new onboarding flow",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-12T21:36:00Z",
          isSeed: true,
        },
        {
          title: "Task039",
          slug: "task039",
          description: "Improve error pages",
          status: "TODO",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-14T06:14:24Z",
          isSeed: true,
        },
        {
          title: "Task043",
          slug: "task043",
          description: "Implement new authentication flow",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "ENHANCEMENT",
          createdAt: "2025-06-15T14:52:48Z",
          isSeed: true,
        },
        {
          title: "Task047",
          slug: "task047",
          description: "Setup staging environment",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-16T23:31:12Z",
          isSeed: true,
        },
        {
          title: "Task051",
          slug: "task051",
          description: "Refactor GraphQL schema",
          status: "DONE",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-18T08:09:36Z",
          isSeed: true,
        },
        {
          title: "Task055",
          slug: "task055",
          description: "Improve SEO tags",
          status: "CANCELED",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-19T16:48:00Z",
          isSeed: true,
        },
        {
          title: "Task059",
          slug: "task059",
          description: "Implement feature flags",
          status: "TODO",
          priority: "HIGH",
          type: "BUG",
          createdAt: "2025-06-21T01:26:24Z",
          isSeed: true,
        },
        {
          title: "Task063",
          slug: "task063",
          description: "Improve build pipeline",
          status: "TODO",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-22T10:04:48Z",
          isSeed: true,
        },
        {
          title: "Task067",
          slug: "task067",
          description: "Add export to CSV",
          status: "DONE",
          priority: "HIGH",
          type: "BUG",
          createdAt: "2025-06-23T18:43:12Z",
          isSeed: true,
        },
        {
          title: "Task071",
          slug: "task071",
          description: "Design new onboarding flow",
          status: "TODO",
          priority: "MEDIUM",
          type: "FEATURE",
          createdAt: "2025-06-25T03:21:36Z",
          isSeed: true,
        },
        {
          title: "Task075",
          slug: "task075",
          description: "Implement feature flags",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-06-26T12:00:00Z",
          isSeed: true,
        },
        {
          title: "Task079",
          slug: "task079",
          description: "Test backup and restore",
          status: "TODO",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-27T20:38:24Z",
          isSeed: true,
        },
        {
          title: "Task083",
          slug: "task083",
          description: "Improve mobile responsiveness",
          status: "TODO",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-29T05:16:48Z",
          isSeed: true,
        },
        {
          title: "Task087",
          slug: "task087",
          description: "Add support for multi-language",
          status: "DONE",
          priority: "MEDIUM",
          type: "OTHER",
          createdAt: "2025-06-30T13:55:12Z",
          isSeed: true,
        },
        {
          title: "Task091",
          slug: "task091",
          description: "Integrate payment provider",
          status: "TODO",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-07-01T22:33:36Z",
          isSeed: true,
        },
        {
          title: "Task095",
          slug: "task095",
          description: "Improve form validation",
          status: "DONE",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-07-03T07:12:00Z",
          isSeed: true,
        },
        {
          title: "Task099",
          slug: "task099",
          description: "Design new onboarding flow",
          status: "TODO",
          priority: "HIGH",
          type: "BUG",
          createdAt: "2025-07-04T15:50:24Z",
          isSeed: true,
        },
      ],
    },
  },
  {
    name: "Patric",
    email: "patric@prisma.io",
    role: "DEVELOPER",
    tasks: {
      create: [
        {
          title: "Task004",
          slug: "task004",
          description: "Migrate to new API version",
          status: "CANCELED",
          priority: "LOW",
          type: "OTHER",
          createdAt: "2025-06-02T08:38:24Z",
          isSeed: true,
        },
        {
          title: "Task008",
          slug: "task008",
          description: "Document public API",
          status: "CANCELED",
          priority: "LOW",
          type: "BUG",
          createdAt: "2025-06-03T17:16:48Z",
          isSeed: true,
        },
        {
          title: "Task012",
          slug: "task012",
          description: "Migrate to new API version",
          status: "TODO",
          priority: "LOW",
          type: "ENHANCEMENT",
          createdAt: "2025-06-05T01:55:12Z",
          isSeed: true,
        },
        {
          title: "Task016",
          slug: "task016",
          description: "Optimize WebSocket connections",
          status: "TODO",
          priority: "MEDIUM",
          type: "BUG",
          createdAt: "2025-06-06T10:33:36Z",
          isSeed: true,
        },
        {
          title: "Task020",
          slug: "task020",
          description: "Enhance code review checklist",
          status: "TODO",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-06-07T19:12:00Z",
          isSeed: true,
        },
        {
          title: "Task024",
          slug: "task024",
          description: "Add skeleton loaders",
          status: "DONE",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-09T03:50:24Z",
          isSeed: true,
        },
        {
          title: "Task028",
          slug: "task028",
          description: "Fix logout redirect bug",
          status: "DONE",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-10T12:28:48Z",
          isSeed: true,
        },
        {
          title: "Task032",
          slug: "task032",
          description: "Migrate to new API version",
          status: "TODO",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-11T21:07:12Z",
          isSeed: true,
        },
        {
          title: "Task036",
          slug: "task036",
          description: "Update dependencies",
          status: "DONE",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-13T05:45:36Z",
          isSeed: true,
        },
        {
          title: "Task040",
          slug: "task040",
          description: "Support custom domains",
          status: "DONE",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-14T14:24:00Z",
          isSeed: true,
        },
        {
          title: "Task044",
          slug: "task044",
          description: "Refactor settings page",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-15T23:02:24Z",
          isSeed: true,
        },
        {
          title: "Task048",
          slug: "task048",
          description: "Write unit tests for billing",
          status: "CANCELED",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-06-17T07:40:48Z",
          isSeed: true,
        },
        {
          title: "Task052",
          slug: "task052",
          description: "Migrate to new API version",
          status: "TODO",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-18T16:19:12Z",
          isSeed: true,
        },
        {
          title: "Task056",
          slug: "task056",
          description: "Refactor notification service",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "BUG",
          createdAt: "2025-06-20T00:57:36Z",
          isSeed: true,
        },
        {
          title: "Task060",
          slug: "task060",
          description: "Support custom domains",
          status: "CANCELED",
          priority: "HIGH",
          type: "ENHANCEMENT",
          createdAt: "2025-06-21T09:36:00Z",
          isSeed: true,
        },
        {
          title: "Task064",
          slug: "task064",
          description: "Fix cache invalidation bug",
          status: "DONE",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-22T18:14:24Z",
          isSeed: true,
        },
        {
          title: "Task068",
          slug: "task068",
          description: "Write end-to-end tests",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "OTHER",
          createdAt: "2025-06-24T02:52:48Z",
          isSeed: true,
        },
        {
          title: "Task072",
          slug: "task072",
          description: "Write end-to-end tests",
          status: "IN_PROGRESS",
          priority: "MEDIUM",
          type: "DOCUMENTATION",
          createdAt: "2025-06-25T11:31:12Z",
          isSeed: true,
        },
        {
          title: "Task076",
          slug: "task076",
          description: "Design new onboarding flow",
          status: "IN_PROGRESS",
          priority: "HIGH",
          type: "ENHANCEMENT",
          createdAt: "2025-06-26T20:09:36Z",
          isSeed: true,
        },
        {
          title: "Task080",
          slug: "task080",
          description: "Refactor GraphQL schema",
          status: "CANCELED",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-06-28T04:48:00Z",
          isSeed: true,
        },
        {
          title: "Task084",
          slug: "task084",
          description: "Design admin dashboard",
          status: "CANCELED",
          priority: "HIGH",
          type: "FEATURE",
          createdAt: "2025-06-29T13:26:24Z",
          isSeed: true,
        },
        {
          title: "Task088",
          slug: "task088",
          description: "Improve offline support",
          status: "TODO",
          priority: "HIGH",
          type: "ENHANCEMENT",
          createdAt: "2025-06-30T22:04:48Z",
          isSeed: true,
        },
        {
          title: "Task092",
          slug: "task092",
          description: "Test rate limiting",
          status: "TODO",
          priority: "LOW",
          type: "DOCUMENTATION",
          createdAt: "2025-07-02T06:43:12Z",
          isSeed: true,
        },
        {
          title: "Task096",
          slug: "task096",
          description: "Integrate payment provider",
          status: "TODO",
          priority: "HIGH",
          type: "DOCUMENTATION",
          createdAt: "2025-07-03T15:21:36Z",
          isSeed: true,
        },
        {
          title: "Task100",
          slug: "task100",
          description: "Implement usage analytics",
          status: "DONE",
          priority: "MEDIUM",
          type: "ENHANCEMENT",
          createdAt: "2025-07-05T00:00:00Z",
          isSeed: true,
        },
      ],
    },
  },
];

export async function main() {
  for (const u of userData) {
    await prisma.user.create({ data: u });
  }
}

main();
